//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank_Platoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public string id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public string platoon_position { get; set; }
        public string g_strat_pos { get; set; }
        public string personal_win_rate { get; set; }
        public string tank { get; set; }
        public string tank_platoon { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string birth_year { get; set; }
        public string nickname { get; set; }
        public string country { get; set; }
        public string colour { get; set; }
    
        public virtual Tank_Platoons Tank_Platoons { get; set; }
        public virtual Tanks Tanks { get; set; }
    }
}
