//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank_Platoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanks
    {
        public Tanks()
        {
            this.Players = new HashSet<Players>();
        }
    
        public string id { get; set; }
        public string tank_name { get; set; }
        public string tier { get; set; }
        public string type { get; set; }
        public string top_speed { get; set; }
        public string tank_nation { get; set; }
        public string image { get; set; }
        public string gun { get; set; }
    
        public virtual Guns Guns { get; set; }
        public virtual ICollection<Players> Players { get; set; }
    }
}
