//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank_Platoons
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPlatoon2Entities1 : DbContext
    {
        public TPlatoon2Entities1()
            : base("name=TPlatoon2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Guns> Guns { get; set; }
        public virtual DbSet<Leagues> Leagues { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tank_Platoons> Tank_Platoons { get; set; }
        public virtual DbSet<Tanks> Tanks { get; set; }
        public virtual DbSet<Tropheys> Tropheys { get; set; }
    }
}
