//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank_Platoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leagues
    {
        public Leagues()
        {
            this.Tropheys = new HashSet<Tropheys>();
        }
    
        public string id { get; set; }
        public string league_name { get; set; }
        public string league_type { get; set; }
        public string league_country { get; set; }
    
        public virtual ICollection<Tropheys> Tropheys { get; set; }
    }
}
