//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank_Platoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tropheys
    {
        public string id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> place { get; set; }
        public string league { get; set; }
        public string tank_platoon { get; set; }
    
        public virtual Leagues Leagues { get; set; }
        public virtual Tank_Platoons Tank_Platoons { get; set; }
    }
}
